# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"
type_run_name: "runs"
run_name: ${now:%Y-%m-%d}_${now:%H-%M-%S} # when using slurm you can pass the job id here

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
